### ISSUE TITLE
SPF testing? Per postfixer?

### ISSUE THREAD

**Issue by mrjcleaver** [sous-chefs/postfix#101]
Hi https://github.com/sumbach/postfixer has a bunch of tests for Postfix ensuring that e.g. DNS and SPF work alongside postfix.

Is this something you would consider in the remit of chef-postfix?

Thanks,
Martin.

**Comment by cmluciano** [comment]
Do you mean adding tests to check if these work well to the cookbook? Kinda like serverspec?

**Comment by mrjcleaver** [comment]
Yes, indeed, something like serverspec.

**Comment by cheeseplus** [comment]
This is welcome as a PR.
