### ISSUE TITLE
postfix 3.3.0 and a relayhost

### ISSUE THREAD

**Issue by bugoff** [sous-chefs/postfix#150]
### Cookbook version
5.3.0

### Chef-client version
14

### Platform Details
ubuntu 18.04

### Scenario:
I configured a relayhost, but since postfix 3.3.0 you need to specify smtpd_recipient_restrictions 

### Steps to Reproduce:
Configure a relayhost on ubuntu 18.04, and you will see this error in the log:

Jul 16 11:53:38 testvm-postfix postfix/smtpd[16498]: fatal: in parameter smtpd_relay_restrictions or smtpd_recipient_restrictions, specify at least one working instance of: reject_unauth_destination, defer_unauth_destination, reject, defer, defer_if_permit or check_relay_domains

### Expected Result:
it should allow you to send a mail through the relayhost

### Actual Result:
postfix is not available on port 25

### Extra question

I could make a MR, but i'm not sure what direction i should use.

Do i check the postfix version? If it's > 3.3.0 then add an extra line in the main.cf? 
Do i configure a default smtpd_recipient_restrictions, if nothing is provided?
i.e. smtpd_recipient_restrictions = permit_mynetworks, reject_unauth_destination, reject

**Comment by arhue** [comment]
Facing this issue too. For now I'm just adding the line with this:
```
ruby_block "insert_line" do
  block do
    file = Chef::Util::FileEdit.new("/etc/postfix/main.cf")
    file.insert_line_if_no_match("/smtpd_recipient_restrictions/", "smtpd_recipient_restrictions = permit_mynetworks, reject_unauth_destination, reject")
    file.write_file
  end
end
```

Any chance for a fix?

**Comment by bugoff** [comment]
@arhue i fixed it by setting this attribute in my wrapper cookbook:

default['postfix']['main']['smtpd_relay_restrictions'] = 'permit_mynetworks, permit_sasl_authenticated, defer_unauth_destination'

**Comment by arhue** [comment]
@bugoff That works way better. Thank you!
